/**
 * The extraction benchmark corpus, as the app carries it.
 *
 * GENERATED by tools/build-extract-corpus.py from eval/cases.json.
 * Do not edit by hand -- a test fails the build if the two disagree.
 *
 * Each case is a piece of source text plus the events a human says are
 * genuinely in it. The `note` explaining WHY each case exists is stripped:
 * that is for a person reading the repo, not for the runtime.
 *
 * Why the app carries this: the API key lives in the phone's browser storage,
 * so a desktop script cannot reach the provider actually in use. The only
 * place this benchmark can measure what Logan really runs is here.
 *
 * THE CASES ARE STILL SYNTHETIC SEEDS. They cover the failure modes the prompt
 * was designed against; they are not real family paperwork. Ten real labelled
 * flyers would be worth more than all of them. See eval/cases.json.
 */

export const EXTRACT_BENCH = {
  cases: [
    {"id": "deadline-vs-event", "today": "2026-08-20", "source": "CHAPEL LAKES ELEMENTARY — Fall Volleyball\n\nTryouts begin Monday, August 24 at 4:00 PM in the North Gym.\nAll athletes must have a completed physical form on file. Forms are due to the front office no later than Friday, August 21.\nBring water, athletic shoes and a completed form. Questions: coach Alvarez.", "expected": [{"title": "Physical form due", "date": "2026-08-21", "kind": "deadline", "notes": "Completed physical form due to the front office; required before tryouts."}, {"title": "Volleyball Tryouts", "date": "2026-08-24", "time": "16:00", "kind": "event", "location": "North Gym", "notes": "Bring water, athletic shoes and a completed physical form."}]},
    {"id": "vague-date-must-not-resolve", "today": "2026-08-20", "source": "PTA Newsletter\n\nThe book fair returns later this fall — dates to be announced.\nPicture day is Wednesday, September 9. Order envelopes went home Tuesday; exact change only.\nWe are still looking for volunteers for the fall festival sometime in October.", "expected": [{"title": "Picture Day", "date": "2026-09-09", "kind": "event", "notes": "Order envelopes went home Tuesday; exact change only."}]},
    {"id": "schedule-grid", "today": "2026-08-20", "source": "DANCE INTENSIVE — Week of Sept 14\n\nTime | Mon Sept 14 | Tue Sept 15\n9:00 | Ballet (Marla) | Ballet (Marla)\n10:30 | Mini Jazz (Austin) | Tap (Austin)\n12:00 | Lunch | Lunch\n1:00 | | Mini M.T. (Austin)\n\nWear all black. Hair up. Bring water and a healthy snack.", "expected": [{"title": "Ballet (Marla)", "date": "2026-09-14", "time": "09:00", "kind": "event", "notes": "Wear all black; hair up; bring water and a healthy snack."}, {"title": "Mini Jazz (Austin)", "date": "2026-09-14", "time": "10:30", "kind": "event", "notes": "Wear all black; hair up; bring water and a healthy snack."}, {"title": "Ballet (Marla)", "date": "2026-09-15", "time": "09:00", "kind": "event", "notes": "Wear all black; hair up; bring water and a healthy snack."}, {"title": "Tap (Austin)", "date": "2026-09-15", "time": "10:30", "kind": "event", "notes": "Wear all black; hair up; bring water and a healthy snack."}, {"title": "Mini M.T. (Austin)", "date": "2026-09-15", "time": "13:00", "kind": "event", "notes": "Wear all black; hair up; bring water and a healthy snack."}]},
    {"id": "notes-live-elsewhere", "today": "2026-08-20", "source": "Subject: Field trip — Thursday\n\nHi families,\n\nOur trip to the science museum is Thursday, September 3. The bus leaves at 8:15 AM sharp from the front loop.\n\nA reminder that permission slips were due last week — if you have not sent one, your child cannot ride.\n\nStudents should wear their class t-shirt and closed-toe shoes, and bring a sack lunch in a disposable bag. No money is needed; admission is covered.", "expected": [{"title": "Science museum field trip", "date": "2026-09-03", "time": "08:15", "kind": "event", "location": "front loop", "notes": "Bus leaves 8:15 AM sharp; wear class t-shirt and closed-toe shoes; bring a sack lunch in a disposable bag; no money needed; permission slip required to ride."}]},
    {"id": "time-range", "today": "2026-08-20", "source": "Open House — Tuesday, September 8, 6:00-8:30 PM in the cafeteria. Drop in any time.", "expected": [{"title": "Open House", "date": "2026-09-08", "time": "18:00", "endTime": "20:30", "kind": "event", "location": "cafeteria", "notes": "Drop in any time."}]},
    {"id": "nothing-to-extract", "today": "2026-08-20", "source": "Thank you to everyone who helped at last week's fun run! We raised more than expected and the kids had a wonderful time. Photos are on the school website. Have a great weekend.", "expected": []},
    {"id": "weekday-and-date-disagree", "today": "2026-08-20", "source": "Band practice moves to Wenesday 9/2 at 3:30 in the band room. Bring your folder.", "expected": [{"title": "Band practice", "date": "2026-09-02", "time": "15:30", "kind": "event", "location": "band room", "notes": "Bring your folder."}]},
    {"id": "two-deadlines-one-day", "today": "2026-08-20", "source": "Reminders for Friday, August 28: yearbook orders close at midnight, and spirit-wear payment is due to the office by 3 PM.", "expected": [{"title": "Yearbook orders close", "date": "2026-08-28", "kind": "deadline", "notes": "Orders close at midnight."}, {"title": "Spirit-wear payment due", "date": "2026-08-28", "kind": "deadline", "notes": "Payment due to the office by 3 PM."}]}
  ],
};
