#!/usr/bin/env python3
"""Generate js/extract-cases.js from eval/cases.json.

The extraction benchmark became runnable from inside the app in v9.19, so the
corpus has to ship. Every `note` is stripped: those are the human reasons a
case exists, written for someone reading the repo, and they are dead weight in
a download. The labels themselves ship unchanged, so a run on the phone and a
run from the terminal are scored against the same answers.

Generated, never hand-edited. A test fails the build if the two drift.
"""
import json

src = json.load(open('eval/cases.json'))
cases = [{'id': c['id'], 'today': c['today'], 'source': c['source'], 'expected': c['expected']}
         for c in src['cases']]

lines = ',\n'.join('    ' + json.dumps(c, ensure_ascii=False) for c in cases)
out = '''/**
 * The extraction benchmark corpus, as the app carries it.
 *
 * GENERATED by tools/build-extract-corpus.py from eval/cases.json.
 * Do not edit by hand -- a test fails the build if the two disagree.
 *
 * Each case is a piece of source text plus the events a human says are
 * genuinely in it. The `note` explaining WHY each case exists is stripped:
 * that is for a person reading the repo, not for the runtime.
 *
 * Why the app carries this: the API key lives in the phone's browser storage,
 * so a desktop script cannot reach the provider actually in use. The only
 * place this benchmark can measure what Logan really runs is here.
 *
 * THE CASES ARE STILL SYNTHETIC SEEDS. They cover the failure modes the prompt
 * was designed against; they are not real family paperwork. Ten real labelled
 * flyers would be worth more than all of them. See eval/cases.json.
 */

export const EXTRACT_BENCH = {
  cases: [
%s
  ],
};
''' % lines
open('js/extract-cases.js', 'w').write(out)
print('wrote js/extract-cases.js (%d cases, %d bytes)' % (len(cases), len(out)))
